//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "account_status")]
pub enum AccountStatus {
    #[sea_orm(string_value = "disabled")]
    Disabled,
    #[sea_orm(string_value = "enabled")]
    Enabled,
}
